export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FALIED = 'FETCH_PRODUCTS_FALIED';

export const INCREMENT_QAUNTITY = 'INCREMENT_QAUNTITY';
export const DECREMENT_QAUNTITY = 'DECREMENT_QAUNTITY';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FORM_CART = 'REMOVE_FORM_CART';
