export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FALIED = 'FETCH_PRODUCTS_FALIED';

export const ADD_TO_CART = 'ADD_TO_CART';
